export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_REFRESH = 'AUTH_REFRESH';

export const LOG_OUT = 'LOG_OUT';

export const AMEND_AUTH_START = 'AMEND_AUTH_START';
export const AMEND_AUTH_SUCCESS = 'AMEND_AUTH_SUCCESS';
export const AMEND_AUTH_FAIL = 'AMEND_AUTH_FAIL';
export const AMEND_AUTH_REFRESH = 'AMEND_AUTH_REFRESH';

export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const SIGNUP_REFRESH = 'SIGNUP_REFRESH';



export const POST_USER_START = 'POST_USER_START';
export const POST_USER_SUCCESS = 'POST_USER_SUCCESS';
export const POST_USER_FAIL = 'POST_USER_FAIL';
export const POST_USER_REFRESH = 'POST_USER_REFRESH';
//TRAIN........

export const POST_TRAIN_START = 'POST_TRAIN_START';
export const POST_TRAIN_SUCCESS = 'POST_TRAIN_SUCCESS';
export const POST_TRAIN_FAIL = 'POST_TRAIN_FAIL';
export const POST_TRAIN_REFRESH = 'POST_TRAIN_REFRESH';

export const TRAIN_BOOKING_START = 'TRAIN_BOOKING_START';
export const TRAIN_BOOKING_SUCCESS = 'TRAIN_BOOKING_SUCCESS';
export const TRAIN_BOOKING_FAIL = 'TRAIN_BOOKING_FAIL';
export const TRAIN_BOOKING_REFRESH = 'TRAIN_BOOKING_REFRESH';


export const GET_TRAIN_START = 'GET_TRAIN_START';
export const GET_TRAIN_SUCCESS = 'GET_TRAIN_SUCCESS';
export const GET_TRAIN_FAIL = 'GET_TRAIN_FAIL';
export const GET_TRAIN_REFRESH = 'GET_TRAIN_REFRESH';



export const GET_TRAIN_TICKET_START = 'GET_TRAIN_TICKET_START';
export const GET_TRAIN_TICKET_SUCCESS = 'GET_TRAIN_TICKET_SUCCESS';
export const GET_TRAIN_TICKET_FAIL = 'GET_TRAIN_TICKET_FAIL';
export const GET_TRAIN_TICKET_REFRESH = 'GET_TRAIN_TICKET_REFRESH';

export const DESTROY_TRAIN_TICKET_START = 'DESTROY_TRAIN_TICKET_START';
export const DESTROY_TRAIN_TICKET_SUCCESS = 'DESTROY_TRAIN_TICKET_SUCCESS';
export const DESTROY_TRAIN_TICKET_FAIL = 'DESTROY_TRAIN_TICKET_FAIL';
export const DESTROY_TRAIN_TICKET_REFRESH = 'DESTROY_TRAIN_TICKET_REFRESH';

export const DESTROY_TRAIN_START = 'DESTROY_TRAIN_START';
export const DESTROY_TRAIN_SUCCESS = 'DESTROY_TRAIN_SUCCESS';
export const DESTROY_TRAIN_FAIL = 'DESTROY_TRAIN_FAIL';
export const DESTROY_TRAIN_REFRESH = 'DESTROY_TRAIN_REFRESH';

export const AMEND_TRAIN_START = 'AMEND_TRAIN_START';
export const AMEND_TRAIN_SUCCESS = 'AMEND_TRAIN_SUCCESS';
export const AMEND_TRAIN_FAIL = 'AMEND_TRAIN_FAIL';
export const AMEND_TRAIN_REFRESH = 'AMEND_TRAIN_REFRESH';


export const AMEND_PROFILE_START = 'AMEND_PROFILE_START';
export const AMEND_PROFILE_SUCCESS = 'AMEND_PROFILE_SUCCESS';
export const AMEND_PROFILE_FAIL = 'AMEND_PROFILE_FAIL';
export const AMEND_PROFILE_REFRESH = 'AMEND_PROFILE_REFRESH';

export const GET_PROFILE_START = 'GET_PROFILE_START';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL';
export const GET_PROFILE_REFRESH = 'GET_PROFILE_REFRESH';

